import { Book } from './types';

export const platformBooks: Record<string, Book[]> = {
  'z-library': [
    {
      id: 'zlib-1',
      title: 'The Art of Computer Programming',
      author: 'Donald E. Knuth',
      description:
        'A comprehensive multi-volume work on computer programming and algorithms.',
      genre: 'Computer Science',
      publishedYear: 1968,
    },
    {
      id: 'zlib-2',
      title: 'Clean Code',
      author: 'Robert C. Martin',
      description: 'A handbook of agile software craftsmanship.',
      genre: 'Software Engineering',
      publishedYear: 2008,
    },
    {
      id: 'zlib-3',
      title: 'Sapiens: A Brief History of Humankind',
      author: 'Yuval Noah Harari',
      description: "A narrative of humanity's creation and evolution.",
      genre: 'History',
      publishedYear: 2011,
    },
    {
      id: 'zlib-4',
      title: '1984',
      author: 'George Orwell',
      description: 'A dystopian social science fiction novel.',
      genre: 'Fiction',
      publishedYear: 1949,
    },
  ],
  libgen: [
    {
      id: 'libgen-1',
      title: 'Introduction to Algorithms',
      author: 'Thomas H. Cormen',
      description:
        'A comprehensive introduction to algorithms and data structures.',
      genre: 'Computer Science',
      publishedYear: 2009,
    },
    {
      id: 'libgen-2',
      title: 'Artificial Intelligence: A Modern Approach',
      author: 'Stuart Russell',
      description: 'The leading textbook in Artificial Intelligence.',
      genre: 'AI & Machine Learning',
      publishedYear: 2020,
    },
    {
      id: 'libgen-3',
      title: 'The Elements of Statistical Learning',
      author: 'Trevor Hastie',
      description: 'Data mining, inference, and prediction.',
      genre: 'Statistics',
      publishedYear: 2009,
    },
    {
      id: 'libgen-4',
      title: 'Linear Algebra Done Right',
      author: 'Sheldon Axler',
      description: 'An undergraduate textbook on linear algebra.',
      genre: 'Mathematics',
      publishedYear: 2015,
    },
  ],
  'anna-archive': [
    {
      id: 'anna-1',
      title: 'The Cathedral and the Bazaar',
      author: 'Eric S. Raymond',
      description:
        'Musings on Linux and Open Source by an accidental revolutionary.',
      genre: 'Open Source',
      publishedYear: 1999,
    },
    {
      id: 'anna-2',
      title: 'Free as in Freedom',
      author: 'Sam Williams',
      description: "Richard Stallman's crusade for free software.",
      genre: 'Biography',
      publishedYear: 2002,
    },
    {
      id: 'anna-3',
      title: "The Cuckoo's Egg",
      author: 'Cliff Stoll',
      description: 'A true story of international computer espionage.',
      genre: 'Cybersecurity',
      publishedYear: 1989,
    },
    {
      id: 'anna-4',
      title: 'Hackers: Heroes of the Computer Revolution',
      author: 'Steven Levy',
      description: 'The history of the computer revolution.',
      genre: 'Technology History',
      publishedYear: 1984,
    },
  ],
  scribd: [
    {
      id: 'scribd-1',
      title: 'Atomic Habits',
      author: 'James Clear',
      description:
        'An easy & proven way to build good habits & break bad ones.',
      genre: 'Self-Help',
      publishedYear: 2018,
    },
    {
      id: 'scribd-2',
      title: 'The 7 Habits of Highly Effective People',
      author: 'Stephen Covey',
      description: 'Powerful lessons in personal change.',
      genre: 'Business',
      publishedYear: 1989,
    },
    {
      id: 'scribd-3',
      title: 'Thinking, Fast and Slow',
      author: 'Daniel Kahneman',
      description: 'A groundbreaking tour of the mind.',
      genre: 'Psychology',
      publishedYear: 2011,
    },
    {
      id: 'scribd-4',
      title: 'The Lean Startup',
      author: 'Eric Ries',
      description: "How today's entrepreneurs use continuous innovation.",
      genre: 'Entrepreneurship',
      publishedYear: 2011,
    },
  ],
  academia: [
    {
      id: 'academia-1',
      title: 'The Structure of Scientific Revolutions',
      author: 'Thomas Kuhn',
      description: 'A landmark in intellectual history.',
      genre: 'Philosophy of Science',
      publishedYear: 1962,
    },
    {
      id: 'academia-2',
      title: 'On the Origin of Species',
      author: 'Charles Darwin',
      description: 'The foundation of evolutionary biology.',
      genre: 'Biology',
      publishedYear: 1859,
    },
    {
      id: 'academia-3',
      title: 'A Theory of Justice',
      author: 'John Rawls',
      description: 'A work of political philosophy and ethics.',
      genre: 'Philosophy',
      publishedYear: 1971,
    },
    {
      id: 'academia-4',
      title: 'The Wealth of Nations',
      author: 'Adam Smith',
      description:
        'An inquiry into the nature and causes of the wealth of nations.',
      genre: 'Economics',
      publishedYear: 1776,
    },
  ],
  jstor: [
    {
      id: 'jstor-1',
      title: 'The American Economic Review',
      author: 'Various Authors',
      description: 'Leading academic journal in economics.',
      genre: 'Economics Journal',
      publishedYear: 2023,
    },
    {
      id: 'jstor-2',
      title: 'Journal of Political Economy',
      author: 'Various Authors',
      description: 'Academic journal focusing on economic research.',
      genre: 'Economics Journal',
      publishedYear: 2023,
    },
    {
      id: 'jstor-3',
      title: 'The Quarterly Journal of Economics',
      author: 'Various Authors',
      description: 'The oldest professional journal of economics.',
      genre: 'Economics Journal',
      publishedYear: 2023,
    },
    {
      id: 'jstor-4',
      title: 'American Political Science Review',
      author: 'Various Authors',
      description: 'Premier journal of political science.',
      genre: 'Political Science Journal',
      publishedYear: 2023,
    },
  ],
};
